---
- hosts: localhost
  become: yes  # This allows Ansible to execute tasks as sudo
  tasks:
    - name: Ensure curl is installed
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Fetch the Brave GPG key
      ansible.builtin.command:
        cmd: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

    - name: Add the Brave apt repository
      ansible.builtin.copy:
        content: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        dest: /etc/apt/sources.list.d/brave-browser-release.list

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Brave browser
      ansible.builtin.apt:
        name: brave-browser
        state: present
