- hosts: localhost
  become: true
  tasks: 
  - name: Install packages
    apt: name={{item}}
    with_items:
      - tmux
      - awesome
      - fzf
      - ripgrep

  - name: Download Google Chrome .deb
    get_url:
      url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      dest: "/tmp/google-chrome-stable_current_amd64.deb"
      mode: '0775'

  - name: Install Google Chrome
    apt:
      deb: "/tmp/google-chrome-stable_current_amd64.deb"

  - name: Ensure snapd is installed (this is the snap package manager)
    apt:
      name: snapd
      state: present

  - name: Install Spotify
    snap:
      name: spotify
